schema-version: v1
kind: plugin
metadata:
  name: java-springboot-restapi-base
  display-name: java-springboot-restapi-base
  description: Base plugin for bulding REST API applications with Java and Spring Boot
  version: 0.0.1
  picture: plugin-base.png
spec:
  type: app
  compatibility:
    - java
    - spring
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - api
    - docker
    - rest
    - spring boot