schema-version: v1
kind: plugin
metadata:
  name: java-springboot-restapi-base-plugin
  display-name: Java Spring Boot REST API Base Plugin
  description: Base plugin for bulding REST API applications with Java and Spring Boot
  version: 0.0.1
  picture: plugin-base.png
spec:
  type: app
  compatibility:
    - java
    - spring
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - api
    - docker
    - rest
    - spring boot
  inputs:
    - label: Project name
      type: text
      name: project_name
      default: springboot-restapi-app
    - label: Project description
      type: text
      name: project_description
      default: Simple REST API application with Java and Spring Boot
    - label: Spring Boot version
      type: text
      name: project_springboot_version
      default: 2.7.2
    - label: Project groupId
      type: text
      name: project_group_id
    - label: Project artifactId
      type: text
      name: project_artifact_id
    - label: Project version
      type: text
      name: project_version
      default: 0.0.1-SNAPSHOT
  computedInputs:
    "project_base_package": "{{project_group_id}}.{{project_artifact_id}}"
    "project_folder": "{{computed_inputs.project_base_package | replace('.', '/')}}"
    "project_name_capitalized": "{{project_name | regex_replace('[^0-9a-zA-Z]','') | capitalize}}"
  hooks:
    - type: run-script
      trigger: before-input
      script: scripts/regex_replace.py